# Generated by Django 6.0.5 on 2026-07-12 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Criminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('alias', models.CharField(blank=True, max_length=150, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True)),
                ('criminal_history', models.TextField(blank=True, null=True)),
                ('wanted', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('badge_number', models.CharField(max_length=100)),
                ('rank', models.CharField(choices=[('ACP', ' ACP'), ('Inspector', 'Inspector'), ('Superintendent', 'Superintendent')], max_length=20)),
                ('joining_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('case_number', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('date_registered', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Investigating', 'Investigating'), ('Solved', 'Solved'), ('Closed', 'Closed')], max_length=20)),
                ('criminal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='testapp.criminal')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='testapp.officer')),
            ],
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_type', models.CharField(choices=[('Fingerprint', 'Fingerprint'), ('DNA', 'DNA'), ('Weapon', 'Weapon'), ('Photo', 'Photo'), ('Video', 'Video'), ('Document', 'Document')], max_length=30)),
                ('description', models.TextField()),
                ('collected_on', models.DateField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='testapp.case')),
                ('collected_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.officer')),
            ],
        ),
        migrations.CreateModel(
            name='Witness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('statement', models.TextField()),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='witnesses', to='testapp.case')),
            ],
        ),
    ]
