# Generated by Django 6.0.5 on 2026-07-12 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='rank',
            field=models.CharField(choices=[('ACP', ' ACP'), ('Inspector', 'Inspector'), ('Senior Inspector', 'Senior Inspector'), ('Superintendent', 'Superintendent')], max_length=20),
        ),
    ]
