# Generated by Django 6.0.5 on 2026-07-12 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_alter_officer_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='rank',
            field=models.CharField(choices=[('ACP', ' ACP'), ('Inspector', 'Inspector'), ('Senior Inspector', 'Senior Inspector'), ('Superintendent', 'Superintendent'), ('Chief Forensic Expert', 'Chief Forensic Expert'), ('Head of Forensic Lab', 'Head of Forensic Lab')], max_length=200),
        ),
    ]
