# Generated by Django 6.0.5 on 2026-07-12 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_alter_officer_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officer',
            name='badge_number',
        ),
        migrations.AlterField(
            model_name='officer',
            name='rank',
            field=models.CharField(choices=[('ACP', ' ACP'), ('Inspector', 'Inspector'), ('Sub Inspector', 'Sub Inspector'), ('Senior Inspector', 'Senior Inspector'), ('Superintendent', 'Superintendent'), ('Assistant Forensic Expert', 'Assistant Forensic Expert'), ('Lab Assistant', 'Lab Assistant'), ('Chief Forensic Expert', 'Chief Forensic Expert'), ('Head of Forensic Lab', 'Head of Forensic Lab')], max_length=200),
        ),
    ]
