# Generated by Django 6.0.5 on 2026-07-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_alter_officer_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='rank',
            field=models.CharField(choices=[('ACP', ' ACP'), ('High Commission SOS Officer', 'High Commission SOS Officer'), ('Inspector', 'Inspector'), ('Sub Inspector', 'Sub Inspector'), ('Senior Inspector', 'Senior Inspector'), ('Assistant Forensic Expert', 'Assistant Forensic Expert'), ('Senior Forensic Expert', 'Senior Forensic Expert'), ('Lab Assistant', 'Lab Assistant'), ('Chief Forensic Expert', 'Chief Forensic Expert'), ('Head of Forensic Lab', 'Head of Forensic Lab')], max_length=200),
        ),
    ]
