# Generated by Django 6.0.5 on 2026-07-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0008_alter_evidence_evidence_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='evidence_type',
            field=models.CharField(choices=[('Fingerprint', 'Fingerprint'), ('DNA', 'DNA'), ('Weapon', 'Weapon'), ('Photo', 'Photo'), ('Video', 'Video'), ('Document', 'Document'), ('CCTV Footage', 'CCTV Footage'), ('Eye Witness', 'Eye Witness'), ('Voice Recording', 'Voice Recording'), ('Mobile Call Records', 'Mobile Call Records')], max_length=30),
        ),
    ]
